### ISSUE TITLE
docker compose example

### ISSUE THREAD

**Issue by samgerene** [rundqvist/docker-openvpn#9]
it would be great to have a docker-compose example with multiple services where one service makes use of the vpn provided by the openvpn service. Even though i am not an expert i made an attempt to make a starting point

```
version: "3.8"

services:
  openvpn:
    image: index.docker.io/rundqvist/openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - HOST_IP=xyz
      - VPN_PROVIDER=xyz
      - VPN_USERNAME=xyz
      - VPN_PASSWORD=xyz
      - VPN_COUNTRY=xyz
    volumes:
      - vpncache:cache
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 1.0.0.1
```
